config/routes.rb
Rails.application.routes.draw do
  
  
  resources :console_types
  resources :listings   
  resources :games
  resources :users
 

  
  get 'login', to: 'sessions#login'
  post 'login', to: 'sessions#process_login'
  get 'welcome', to: 'sessions#welcome'
  
  post "/login", to: "users#process_login"
  
  post "/listings/:id/buy", to: "listings#buy", as: "buy"
  post "/listings/:id/sell", to: "listings#sell", as: "sell"
  
  
 
 #PATCH "/listings/:id", to: "listing#buying_new_listing_button"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/console_type.rb
class ConsoleType < ApplicationRecord

   has_many :listings
   has_many :users, through: :listings
   has_many :games, through: :listings
end

app/models/game.rb
class Game < ApplicationRecord
    has_many :listings
    has_many :users, through: :listings
    has_many :console_types, through: :listings
end

app/models/listing.rb
class Listing < ApplicationRecord
    #validates :game, uniqueness: true
    belongs_to :console_type
    belongs_to :user
    belongs_to :game
end


 # condition: "like new", "very good", "good", "acceptable"

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :username, presence: true, uniqueness: true
    has_many :listings
    has_many :games, through: :listings
    has_many :console_types, through: :listings
    
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   
     
end

app/controllers/console_types_controller.rb
class ConsoleTypesController < ApplicationController
  
  def index
    @console_types = ConsoleType.all
  end

  def show
    @console_type = ConsoleType.find(params[:id])
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  
  def index
    @games = Game.all
  end
  
  def show 
    @game = Game.find(params[:id])
  end

  def new
    @game = Game.new
  end

  def create
    @game= Game.new(game_strong_params)
    if @game.save
        redirect_to game_path(@game)
    else
        render :new
    end  
  end

  def edit
    @game = Game.find(params[:id])
    render :edit
  end

  def update
    @game= Game.find(params[:id])
         @game.update(game_strong_params)
        if @game.valid?
            redirect_to game_path(@game)
        else   
            render :edit
        end  
  end

  def destroy
    Game.destroy(params[:id])
    redirect_to games_path
  end

  private

  def game_strong_params
    params.require(:game).permit(:name, :developer, :release_date, :rating)
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  def index
    @listings = Listing.all
  end
  
  def show 
    @listing = Listing.find(params[:id])
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing= Listing.new(listing_strong_params)
    if @listing.save
      redirect_to listing_path(@listing)
    else
      render :new
    end  
  end

            # def edit
            #   @listing = Listing.find(params[:id])
            #   render :edit
            # end

            # def update
            #   Listing.find(params[:id])
            #   Listing.update(listing_strong_params)
            #   redirect_to listing_path(@game)
            
            #   render :edit
            # end

            

  def buy
    @listing = Listing.find(params[:id])
    @listing.update(user_id: session[:user_id], availability: false)
    if @listing.valid?
      redirect_to user_path(session[:user_id])
    else
      redirect_to listing_path(@listing)
    end
  end

  def sell
    @listing = Listing.find(params[:id])
    @listing.update(user_id: session[:user_id], availability: true)
    if @listing.valid?
      redirect_to user_path(session[:user_id])
    else
      redirect_to listing_path(@listing)
    end
  end
    
  def destroy
    Listing.destroy(params[:id])
    redirect_to listings_path
  end


  
  private

  def listing_strong_params
    params.require(:listing).permit(:game_id, :user_id, :console_type_id, :quality, :condition, :listed_price, :availability)
  end

end

  

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def login
    render :login
  end

  def process_login
    user = User.find_by(username: params[:username])
    if user
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      
      render :login
    end
  end

  def welcome
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end   
            
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
  end

            # def sell
            #   @listing = Listing.find(params[:id])
            #   @listing.update(user_id: session[:user_id], availability: false)
            #   if @listing.valid?
            #     redirect_to user_path(session[:user_id])
            #   else
            #     redirect_to listing_path(@listing)
            #   end
            # end

  def destroy
    User.destroy(params[:id])
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :age, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/console_types_helper.rb
module ConsoleTypesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/console_types/index.html.erb
<h1> Console types </h1>
<br><br><br>
<%= @console_types.each do |console| %>
  <%= console.name %>
<%end%>

app/views/games/edit.html.erb
 <%= form_for @game do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <%= f.label :developer %>
    <%= f.text_field :developer %>
    <br>
    <%= f.label :release_date %>
    <%= f.text_field :release_date %>
    <br>
    <%= f.label :rating %>
    <%= f.text_field :rating %>
    <br><br>
    <%= f.submit %>
<% end %>

app/views/games/index.html.erb
<div id="demotext">
<h1> Games </h1>
</div>



<%@games.each do |game|%>
   <li><%= link_to game.name, game_path(game) %></li>
<%end%>
<br>

<%= button_to("#{User.find(session[:user_id]).name}'s Homepage", user_path(session[:user_id]),
        method: "get")  %>
       

app/views/games/new.html.erb
 
 <%= form_for @game do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <%= f.label :developer %>
    <%= f.text_field :developer %>
    <br>
    <%= f.label :release_date %>
    <%= f.text_field :release_date %>
    <br>
    <%= f.label :rating %>
    <%= f.text_field :rating %>
    <br><br>
    <%= f.submit "Add Game" %>
<% end %>

app/views/games/show.html.erb
<div id="demotext">
<h1><%="#{@game.name} "%> </h1>
</div>



<p>Developer: <%= @game.developer %></p>
<p>Release Date: <%= @game.release_date %></p>
<p>Rating: <%= @game.rating %></p> 
<br>
<br>


<%= link_to "Edit #{@game.name}", edit_game_path(@game) %> 
<br>
<br>
<%= link_to "List #{@game.name}", new_listing_path() %> 
<br>
<br>

<%= button_to "Delete this game", game_path(@game), :method => :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameShop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>


    
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>



  <body>
 
 
    <%= yield %>
  </body>
</html>

app/views/listings/edit.html.erb
<% if @listing.errors %>
    <% @listing  .errors.full_messages.each do |message| %>
        <div><%= message %></div>
    <% end %>
<% end %>



<%= form_for @listing do |f|%>
<%= f.label :user %>
<%= f.collection_select :user_id, User.all, :id, :name%> 
<br>
<%= f.label :game %>
<%= f.collection_select :game_id, Game.all, :id, :name%> 
<br>
<%= f.label :console_type %>
<%= f.collection_select :console_type_id, ConsoleType.all, :id, :name%> 
<br>
<%= f.label :quality %>
    <%= f.select :quality, ["New", "Used"] %>
<br>
<%= f.label :condition%>
<%= f.text_field :condition %>
<br>
<%= f.label :listed_price%>
<%= f.number_field :listed_price %>

 <%= f.label :availability, "Availability?" %>
    <%= f.select :availability, [true, false] %>
<%= f. submit %></li>
<%end%>
<%end%>

app/views/listings/index.html.erb
<div id="demotext">
<h1>Available Listings</h1>
</div>


<%@listings.each do |listing|%>
    <%if listing.availability == true && listing.user_id != session[:user_id] %>
        <li><%= link_to listing.game.name, listing_path(listing)%></li>
    <%end%>
<%end%>

app/views/listings/new.html.erb
<% if @listing.errors %>
    <% @listing  .errors.full_messages.each do |message| %>
        <div><%= message %></div>
    <% end %>
<% end %>



<%= form_for @listing do |f|%>
<%= f.label :user %>
<%= f.select :user, [User.find(session[:user_id]).name] %> 
<br>
<%= f.label :game %>
<%= f.collection_select :game_id, Game.all, :id, :name%> 
<br>
<%= f.label :console_type %>
<%= f.collection_select :console_type_id, ConsoleType.all, :id, :name%> 
<br>
<%= f.label :condition%>
<%= f.select :condition, ["New", "Like New", "Very Good", "Good", "Acceptable"] %>
<br>
<%= f.label :listed_price%>
<%= f.number_field :listed_price %>
<br>
<%= f.label :availability %>
<%= f.select :availability, ["True"] %>
<br><br>
<%= f. submit %></li>
<%end%>

app/views/listings/show.html.erb
<div id="demotext">

<h1>Details </h1> 
<h3><%=@listing.game.name%></h3>

</div>


Listed: <%= @listing.user.name %> <br>
Console Type: <%= @listing.console_type.name %> <br>
Condition: <%= @listing.condition %> <br>
Listed Price: <%= @listing.listed_price %> <br>
Availability: <%= @listing.availability %> 

<br>
<br>

<% if @listing.availability == true %>
        <%= button_to 'Buy This Listing', buy_path(@listing) %><br>
<%else%> 
        <%= button_to 'Sell This Listing', sell_path(@listing) %><br>
<%end%>

<%= button_to("View Available Listings", listings_path(),
        method: "get") %>
<br>
<%= button_to("#{User.find(session[:user_id]).name}'s Homepage", user_path(session[:user_id]),
        method: "get")  %>

app/views/users/index.html.erb





<div id="demotext">
<h1> All Users </h1>
</div>



<% @users.each do |user| %>
<br>
<div id="demotext"> <%= link_to user.name, user_path(user) %> </div> 
<%end%>



app/views/users/login_form.html.erb
<h1>Login</h1>


 <%= form_for login_path do |f| %>

   <p> <%= f.label :username%>
    <%= f.text_field :username%></p>
   <P> <%= f.label :password%>
    <%= f.password_field :password%></P> 

    <%= f.submit "Login" %>

 
    

app/views/users/new.html.erb
 
 <div id="demotext">
 <h1>Sign Up</h1>
 </div>


 <%= form_for @user do |f| %>
   <p> <%= f.label :name %>
    <%= f.text_field :name %></p>
    
   <p> <%= f.label :username%>
    <%= f.text_field :username%></p>

   <P> <%= f.label :password%>
    <%= f.password_field :password%></P> 

   <P> <%= f.label :age %>
    <%= f.text_field :age %></P>
    
    <%= f.submit "Create Account" %>
<% end %>

app/views/users/show.html.erb

<div id="demotext">
<h1> <%= @user.name %>'s Homepage </h1>
</div>

<div> 
<h3>Age: <%= @user.age %></h3>
<br>
<h3>Games Owned (listings):</h3>
</div>

<ul>
<% @user.listings.each do |listing|%>
  <li><%= link_to listing.game.name, listing_path(listing) %> </li>
<%end%>
</ul>

<br>
<%= link_to "Create Game ", new_game_path() %> 
<br>
<br>
<%= link_to "View Games ", games_path() %> 
<br>
<br>
<%= link_to "Create listing ", new_listing_path() %> 
<br>
<br>
<%= link_to "View listings ", listings_path() %> <br> <br>

<%= button_to "Delete Account", user_path(@user), :method => :delete %><br>


